-- ═══════════════════════════════════════════════════════════════════
-- RBI Banking Fraud Intelligence Platform — Supabase Schema Setup
-- Run this script in your Supabase Dashboard → SQL Editor
-- Project: mmdvlnxbofjrhtnenanc
-- ═══════════════════════════════════════════════════════════════════

-- ── 1. USERS ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.users (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          TEXT NOT NULL,
  email         TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role          TEXT NOT NULL DEFAULT 'analyst',
  created_at    TIMESTAMPTZ DEFAULT NOW(),
  updated_at    TIMESTAMPTZ DEFAULT NOW()
);

-- ── 2. CUSTOMERS ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.customers (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name  TEXT NOT NULL,
  last_name   TEXT NOT NULL,
  email       TEXT NOT NULL,
  phone       TEXT,
  kyc_status  TEXT DEFAULT 'VERIFIED',
  risk_rating TEXT DEFAULT 'LOW',
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- ── 3. ACCOUNTS ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.accounts (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id    BIGINT REFERENCES public.customers(id) ON DELETE CASCADE,
  account_number TEXT UNIQUE NOT NULL,
  account_type   TEXT NOT NULL DEFAULT 'SAVINGS',
  balance        NUMERIC(15, 2) DEFAULT 0.00,
  currency       TEXT DEFAULT 'INR',
  status         TEXT DEFAULT 'ACTIVE',
  created_at     TIMESTAMPTZ DEFAULT NOW()
);

-- ── 4. TRANSACTIONS ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.transactions (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id       BIGINT REFERENCES public.accounts(id) ON DELETE CASCADE,
  amount           NUMERIC(15, 2) NOT NULL,
  currency         TEXT DEFAULT 'INR',
  transaction_type TEXT NOT NULL,
  merchant_name    TEXT,
  location         TEXT,
  device_id        TEXT,
  ip_address       TEXT,
  rule_score       FLOAT DEFAULT 0.0,
  ml_probability   FLOAT DEFAULT 0.0,
  risk_score       FLOAT DEFAULT 0.0,
  risk_level       TEXT DEFAULT 'Low',
  triggered_rules  TEXT,
  status           TEXT DEFAULT 'APPROVED',
  created_at       TIMESTAMPTZ DEFAULT NOW()
);

-- ── 5. FRAUD ALERTS ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.fraud_alerts (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_id BIGINT REFERENCES public.transactions(id) ON DELETE CASCADE,
  risk_score     FLOAT NOT NULL,
  risk_level     TEXT NOT NULL,
  status         TEXT DEFAULT 'OPEN',
  assigned_to    BIGINT REFERENCES public.users(id),
  created_at     TIMESTAMPTZ DEFAULT NOW(),
  updated_at     TIMESTAMPTZ DEFAULT NOW()
);

-- ── 6. INVESTIGATIONS ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.investigations (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alert_id    BIGINT REFERENCES public.fraud_alerts(id) ON DELETE CASCADE,
  analyst_id  BIGINT REFERENCES public.users(id),
  notes       TEXT NOT NULL,
  outcome     TEXT NOT NULL,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- ── 7. FRAUD RULES ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.fraud_rules (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_code   TEXT UNIQUE NOT NULL,
  rule_name   TEXT NOT NULL,
  category    TEXT NOT NULL,
  description TEXT,
  weight      FLOAT DEFAULT 1.0,
  threshold   FLOAT DEFAULT 50000.0,
  is_active   INT DEFAULT 1,
  parameters  TEXT,
  updated_at  TIMESTAMPTZ DEFAULT NOW()
);

-- ── 8. AUDIT LOGS ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     BIGINT,
  action      TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id   TEXT,
  details     TEXT,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────
-- Disable Row Level Security so the anon key can read/write all tables
-- ─────────────────────────────────────────────────────────────────────
ALTER TABLE public.users          DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers      DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.accounts       DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions   DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.fraud_alerts   DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.investigations DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.fraud_rules    DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs     DISABLE ROW LEVEL SECURITY;

-- Grant full permissions to anon and authenticated roles
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon;
GRANT ALL ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;
